### ISSUE TITLE
Favicons on Feedly no longer appearing

### ISSUE THREAD

**Issue by jminiman** [jmlntw/feedly-faviconize-list#11]
I believe Feedly changed something on their end; will you please research and see what has changed thereby breaking your excellent script? I am using Chrome 111 on macOS 12.6.3 with Tampermonkey 4.18.1.

**Comment by mnghsn** [comment]
Fixed in #10 and [v0.2.7](https://github.com/jmlntw/feedly-faviconize-list/tree/v0.2.7).

**Comment by jminiman** [comment]
Looks good on my end - thank you!
